# Generated by Django 5.1.3 on 2024-12-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_banners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='alt_text',
            field=models.CharField(max_length=500),
        ),
    ]
