# Generated by Django 5.1.3 on 2024-12-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_alter_banners_alt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='monthly_fee',
            field=models.IntegerField(default=400000),
        ),
    ]
