# Generated by Django 5.1.3 on 2024-12-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_user_user_name_alter_membership_monthly_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('trainer', 'Trainer'), ('member', 'Member'), ('admin', 'Admin')], default='member', max_length=20),
        ),
    ]
