# Generated by Django 5.1.3 on 2024-12-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_remove_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='class_id',
            field=models.CharField(default='', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
